import { createRequire } from "module";
const require = createRequire(import.meta.url);
const express = require("express");
const router = express.Router();

import { router as dashboardRouter } from "./dashboard.js";
import { router as seusRouter } from "./seus.js";
import { router as packsRouter } from "./packs.js";
import { router as templateRegistryRouter } from "./templateRegistry.js";
import { router as profileRegistryRouter } from "./profileRegistry.js";
import { router as deliverableDefinitionRegistryRouter } from "./deliverableDefinitionRegistry.js";
import { router as serviceDefinitionRegistryRouter } from "./serviceDefinitionRegistry.js";
import { router as policyDefinitionRegistryRouter } from "./policyDefinitionRegistry.js";
import { router as objectivesRouter } from "./objectives.js";
import { router as servicesRouter } from "./services.js";
import { router as knowledgeRouter } from "./knowledge.js";
import { router as telemetryRouter } from "./telemetry.js";
import { router as attentionRouter } from "./attention.js";
import { router as identityRouter } from "./identity.js";
import { router as sdkAuthoringRouter } from "./sdkAuthoring.js";
import { router as schemaRegistryRouter } from "./schemaRegistry.js";
import { router as ontologyRouter } from "./ontology.js";
import { router as workQueueRouter } from "./workQueue.js";
import { router as reviewsRouter } from "./reviews.js";
import { router as complianceRouter } from "./compliance.js";
import { router as devActAsRouter } from "./devActAs.js";
import { router as eventsRouter } from "./events.js";

router.use(dashboardRouter);
router.use(objectivesRouter);
router.use(seusRouter);
router.use(packsRouter);
router.use(templateRegistryRouter);
router.use(profileRegistryRouter);
router.use(deliverableDefinitionRegistryRouter);
router.use(serviceDefinitionRegistryRouter);
router.use(policyDefinitionRegistryRouter);
router.use(servicesRouter);
router.use(knowledgeRouter);
router.use(telemetryRouter);
router.use(attentionRouter);
router.use(identityRouter);
router.use(schemaRegistryRouter);
router.use(ontologyRouter);
router.use(sdkAuthoringRouter);
router.use(workQueueRouter);
router.use(reviewsRouter);
router.use(complianceRouter);
router.use(devActAsRouter);
router.use(eventsRouter);

export { router };
