-- Ontology (Ch.18) — capability-name concepts, reworked (CR-086 step one).
-- Owner, 2026-08-18: "Capability packs are essentially process fragments done
-- by a team... The platform uses code to identify the process fragment. The
-- tenants may use the same process, but call it by a different name."
--
-- This migration replaces the original 23-row seed outright with the
-- vocabulary from Book 3 Ch.10's "Capability" table (design/foundations/03_
-- Book 3 (Refined)/02_Part 2/Chapter 10.md) — a full generational rewrite of
-- the concept_type, not an amendment to it. CR-086 confirmed there are still
-- zero consumers of capability-name concepts anywhere in the codebase (the
-- functional `capabilities` table — one row per Pack contributing a
-- capability — is a separate, unrelated structure; see CR-085), so this
-- replace has zero blast radius on running code.
--
-- Naming discipline unchanged from the original migration (owner: "simple
-- rules. small case no spaces"): code is lowercase-hyphenated, default_label
-- carries the exact human wording. DELETE-then-INSERT (rather than the
-- original's rename-in-place UPDATE) makes this migration naturally
-- idempotent across replays — no defensive guards needed against a
-- resurrected stale row, unlike the original's CR-059 workaround.

-- DELETE FROM ontology_concepts WHERE concept_type = 'capability-name';

INSERT INTO ontology_concepts (concept_type, code, default_label, description, tenant_id) VALUES
  ('capability-name', 'requirements-elicitation', 'Requirements Elicitation', 'Systematically discover and capture stakeholder needs, business objectives, constraints, and expectations from relevant sources and express them as candidate requirements for subsequent analysis and validation.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'understanding-business-domain', 'Understanding business domain', 'Establish, model, validate, and maintain a shared understanding of the business domain, including its concepts, terminology, entities, relationships, processes, rules, roles, and constraints, so that engineering decisions are grounded in accurate domain knowledge.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'requirements-analysis', 'Analysing engineering requirements', 'examine, structure, refine, model, and reason about elicited requirements to establish their meaning, relationships, dependencies, conflicts, constraints, priorities, and implications, producing a coherent requirements specification suitable for validation and subsequent engineering.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'requirements-validation', 'Validating engineering requirements', 'establish that analysed requirements accurately represent intended business and stakeholder needs and are correct, complete, consistent, feasible, unambiguous, verifiable, traceable, and appropriately agreed before being established as the authoritative engineering baseline.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'modelling-complex-systems', 'Modelling complex systems', 'create, analyse, and maintain coherent structural and behavioural representations of a system, its context, interactions, dependencies, and constraints, so that system complexity can be understood and used as a reliable basis for architectural and engineering decisions.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'architecture-design', 'Designing software architecture', 'determine, evaluate, document, and maintain the fundamental structure of a software system, including its major components, responsibilities, interfaces, interactions, architectural patterns, constraints, and significant design decisions, so that validated requirements and business objectives can be realised within acceptable engineering risk', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'software-construction', 'Constructing software systems', 'transform architectural and detailed design specifications into working software components and implementation artefacts through coding, configuration, generation, and use of appropriate software assets, while maintaining conformance with applicable requirements, architecture, and engineering standards', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'software-design', 'Designing software components', 'decompose architectural elements into implementable software components and determine their responsibilities, interfaces, behaviour, internal structure, dependencies, and design constraints so that they can be constructed consistently with the architecture and allocated requirements', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'engineering-configuration', 'Managing engineering configuration', 'establish and maintain controlled configuration items, baselines, versions, dependencies, and configuration status throughout the engineering lifecycle, ensuring that authorised changes are incorporated consistently and that the composition of any engineering product or environment can be determined and reproduced.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'software-validation', 'Verifying software quality', 'systematically examine and test software and associated engineering artefacts against defined requirements, specifications, standards, and quality criteria, producing objective evidence of conformance and identifying deviations that require resolution.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'engineering-documentation', 'Documenting engineering work', 'create, maintain, organise, and retrieve authoritative records of engineering activities, decisions, artefacts, rationale, and evidence throughout the engineering lifecycle, ensuring that relevant engineering knowledge is understandable, traceable, and available to those who need it.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'protect-organisational-assets', 'Protecting organisational assets', 'identify organisational assets and their protection requirements, assess threats and vulnerabilities, establish and apply appropriate protective controls, and monitor their effectiveness so that assets remain protected against unauthorised access, misuse, damage, loss, compromise, or disruption', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'governing-engineering-decisions', 'Governing engineering decisions', 'establish decision-making authority, criteria, processes, and controls for significant engineering decisions, and to ensure that such decisions are appropriately evaluated, authorised, recorded, and subject to review throughout the engineering lifecycle.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'software-release', 'Managing software release', 'plan, assemble, assess, authorise, and control the release of identified software configurations into their intended environments, ensuring that release prerequisites are satisfied, the released configuration is known and reproducible, and the transition is performed in a controlled manner', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'operating-production-systems', 'Operating production systems', 'operate, monitor, maintain, support, and control software systems in their production environments, ensuring that services remain available, perform as required, remain secure, and respond appropriately to operational events and changing conditions', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'recovering-organisational-knowledge', 'Recovering organisational knowledge', 'locate, retrieve, reconstruct, and contextualise existing organisational knowledge from available records, artefacts, systems, and other sources so that previously established knowledge can be made accessible and usable for current engineering and organisational needs.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'learning', 'Learning from operational experience', 'systematically capture, analyse, and synthesise operational experience, incidents, problems, performance data, and other operational evidence into actionable lessons and improvements for engineering, operations, and organisational practice.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'engineering-practice-improvement', 'Improving engineering practice', 'systematically evaluate engineering practices using experience, evidence, performance information, and identified deficiencies, and to develop, validate, adopt, and maintain improvements to the methods, processes, standards, and practices used to perform engineering work.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'adapting-business-needs', 'Adapting to changing business need', 'detect and assess changes in business objectives, priorities, operating conditions, and organisational needs, determine their implications for engineering capabilities and systems, and realign engineering direction, resources, and priorities so that engineering remains relevant to the business.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-architectural-analysis', 'Continuous architectural analysis', 'continuously analyse the evolving architecture of software systems against their requirements, architectural principles, constraints, dependencies, and operational evidence, identifying architectural risks, deviations, degradation, and emerging implications early enough to support corrective or evolutionary decisions', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'real-time-organisational-documentation', 'Real-time organisational documentation', 'continuously capture, update, organise, and maintain organisational knowledge and engineering information as work occurs and changes are made, keeping authoritative documentation closely synchronised with the current state of the organisation, its systems, decisions, and practices.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'automatic-traceability-generation', 'Automatic traceability generation', 'automatically identify and maintain traceable relationships among engineering artefacts, including requirements, designs, architecture, implementation, tests, defects, and releases, so that dependencies, lineage, coverage, and impact relationships can be determined throughout the engineering lifecycle.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'legacy-modernisation', 'Knowledge recovery from legacy systems (Specialisation from “Recovering organisational knowledge”)', NULL, '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-compliance-verification', 'Continuous compliance verification', NULL, '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'engineering-decision-explainability', 'Engineering decision explainability', NULL, '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'evidence-based-organisational-reasoning', 'Evidence-based organisational reasoning', NULL, '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-requirements-validation', 'Continuous requirements validation', 'continuously evaluate requirements against current business and stakeholder needs, system context, engineering constraints, and evolving implementation evidence, detecting invalid, obsolete, conflicting, incomplete, or otherwise non-conforming requirements early enough to support corrective action.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'predictive-engineering-risk-assessment', 'Predictive engineering risk assessment', 'analyse current and historical engineering information to identify emerging risk patterns, forecast the likelihood and potential impact of future engineering risks, and provide early risk assessments that support preventive action and engineering decision-making.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-quality-assurance', 'Continuous quality assurance', 'continuously monitor and assess the quality of engineering processes, artefacts, and outcomes against defined requirements, standards, policies, and quality criteria, providing ongoing evidence of quality status and initiating corrective action when deviations are detected.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'organisational-memory-synthesis', 'Organisational memory synthesis across multiple projects', 'aggregate, relate, and synthesise knowledge from multiple projects and their engineering artefacts, experiences, decisions, and outcomes to identify reusable organisational knowledge, cross-project patterns, dependencies, lessons, and insights.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-organisational-learning', 'Continuous organisational learning', 'continuously capture and synthesise organisational experience and knowledge, evaluate its implications, incorporate validated learning into organisational knowledge, practices, decisions, and capabilities, and assess whether the resulting changes improve organisational outcomes.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'autonomous-capability-optimisation', 'Autonomous capability optimisation', 'continuously assess organisational capability performance and autonomously identify, evaluate, prioritise, and implement changes to capability structure, capacity, processes, resources, and supporting mechanisms in order to improve organisational outcomes within defined objectives, constraints, and governance controls.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'enterprise-wide-engineering-impact-analysis', 'Enterprise-wide engineering impact analysis', 'analyse the relationships and dependencies across the organisation''s engineering systems, capabilities, projects, assets, and processes to determine the direct and indirect effects of proposed changes or conditions, including affected stakeholders, requirements, architecture, resources, risks, and downstream activities.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-stakeholder-intent-reconciliation', 'Continuous stakeholder-intent reconciliation', 'continuously capture and analyse evolving stakeholder intentions, compare them with established requirements and with one another, identify conflicts, ambiguities, and divergences, and facilitate their resolution so that the engineering baseline remains aligned with the current and collectively agreed stakeholder intent.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-domain-model-drift-detection', 'Continuous domain-model drift detection', 'continuously monitor changes in the business domain and compare them with the established domain model, identifying changes, inconsistencies, omissions, or obsolete representations that cause the model to diverge from the domain it represents.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'predictive-architectural-obsolescence-detection', 'Predictive architectural obsolescence detection (Specialisation from “Predictive engineering risk assessment”)', 'continuously analyse architectural technologies, dependencies, patterns, constraints, support lifecycles, and external technology trends to predict emerging architectural obsolescence and provide sufficient early warning for architectural remediation, replacement, or evolution.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'cross-system-structural-pattern-recognition', 'Cross-system structural pattern recognition', 'analyse and compare the structures of multiple software systems and identify recurring, significant, or anomalous structural patterns across their architectures, components, interfaces, dependencies, and other engineering relationships.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'cross-codebase-pattern-propagation', 'Cross-codebase pattern propagation', 'identify engineering patterns or improvements that are applicable across multiple codebases, determine their affected locations and contextual variations, and propagate the approved pattern or change across those codebases while preserving correctness, consistency, and local compatibility.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-configuration-drift-detection', 'Continuous configuration drift detection', 'continuously monitor and compare actual software, infrastructure, environment, and configuration states against authorised configuration baselines and policies, detecting, assessing, and reporting deviations so that configuration integrity can be maintained.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'predictive-test-coverage-gap-detection', 'Predictive test-coverage gap detection (Specialisation from “Predictive engineering risk assessment”)', 'analyse software structure, requirements, changes, dependencies, existing test assets, and historical verification evidence to predict areas where test coverage is likely to be insufficient, identify the nature and significance of the anticipated gaps, and provide early direction for additional verification.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-vulnerability-posture-assessment', 'Continuous vulnerability posture assessment', 'continuously identify, assess, correlate, and monitor vulnerabilities across organisational technology assets and their environments, determine their significance and exposure, and maintain an up-to-date view of the organisation''s vulnerability posture to support prioritised remediation and risk decisions.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'predictive-threat-pattern-anticipation', 'Predictive threat-pattern anticipation', 'continuously analyse threat intelligence, historical security events, emerging attack techniques, vulnerabilities, system characteristics, and environmental signals to identify and forecast threat patterns that are likely to affect organisational assets, providing early warning to support preventive security action.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-policy-conflict-detection', 'Continuous policy-conflict detection', 'continuously analyse applicable policies, rules, standards, and controls and their relationships to identify conflicting, contradictory, or mutually incompatible requirements, determine the affected engineering activities or decisions, and provide timely evidence for policy resolution.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-release-risk-management', 'Continuous release-risk forecasting', 'continuously analyse release contents, changes, dependencies, verification evidence, defects, configuration, operational conditions, and historical release outcomes to forecast the likelihood and potential impact of release-related problems and provide early risk information for release decisions.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'predictive-incident-anticipation', 'Predictive incident anticipation', 'continuously analyse operational conditions, system behaviour, telemetry, changes, dependencies, historical incidents, and other relevant signals to identify patterns indicating that an operational incident is likely to occur, assess its potential impact, and provide early warning to support preventive or mitigating action.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'autonomous-root-cause-synthesis', 'Autonomous root-cause synthesis', 'autonomously correlate and analyse evidence from incidents, system behaviour, telemetry, changes, configurations, dependencies, defects, and engineering records to identify, evaluate, and synthesise probable root causes and their causal relationships, providing an explainable basis for corrective action.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'autonomous-standard-synthesis', 'Autonomous standard synthesis (Specialisation from “Improving engineering practice”)', 'autonomously analyse engineering practices, organisational knowledge, experience, policies, existing standards, and evidence to identify recurring principles and formulate, evaluate, and maintain candidate standards for adoption within the organisation.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'cross-organisational-capability-benchmarking', 'Cross-organisational capability benchmarking', 'systematically compare organisational capabilities and their performance against relevant external organisations or established benchmarks, using comparable measures and contextual information to determine relative capability position and identify opportunities for improvement.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'continuous-objective-alignment-monitoring', 'Continuous objective-alignment monitoring', 'continuously monitor and evaluate the alignment of engineering activities, decisions, systems, investments, and outcomes with established business and organisational objectives, detecting divergence, loss of relevance, or conflicting priorities early enough to support corrective action.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'business-analysis-approach', 'Planning the business analysis approach', 'determine and establish the methods, activities, techniques, roles, responsibilities, deliverables, timing, and governance by which business analysis will be conducted for an initiative, taking into account its context, objectives, complexity, constraints, and stakeholder environment.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'requirements-prioritising', 'Prioritising engineering requirements', 'evaluate and establish the relative priority of engineering requirements using defined business, stakeholder, technical, risk, regulatory, dependency, cost, and other relevant criteria, so that requirements can be appropriately sequenced and resources directed toward the most important outcomes.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'solution-options', 'Recommending solution options by value', 'identify and evaluate alternative solution options against business objectives, stakeholder needs, expected benefits, costs, risks, constraints, and other relevant criteria, and to recommend the option or combination of options that provides the most appropriate overall value.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'integrating-constructed-components', 'Integrating constructed components', 'combine independently constructed software components and assemblies into progressively larger, coherent subsystems and systems, ensuring that their interfaces, dependencies, interactions, and configurations conform to the defined integration specifications.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'engineering-assets-reuse', 'Reusing existing engineering assets', 'identify potentially reusable engineering assets, assess their suitability, quality, security, compatibility, provenance, licensing, and lifecycle status, and select and incorporate appropriate assets into engineering solutions where reuse provides an acceptable alternative to new construction.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'engineering-work-review', 'Reviewing engineering work', 'independently examine engineering artefacts, activities, and decisions against applicable requirements, standards, policies, and review criteria, identify and communicate deficiencies or deviations, and determine whether the reviewed work is acceptable for progression or requires correction and re-review.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'corrective-actions', 'Eliminating recurring operational problems', 'systematically identify recurring operational problems, analyse their underlying causes, implement and track permanent corrective actions, and verify that the causes have been eliminated or adequately controlled so that the problems do not recur.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'defect-management', 'Managing defects to resolution', 'systematically capture, classify, assess, prioritise, assign, track, resolve, and close software defects, ensuring that resolutions are verified and that defects that cannot yet be resolved are explicitly deferred, owned, and controlled.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'vendor-supplier-management', 'Managing external vendors and suppliers', 'establish and manage relationships with external vendors, suppliers, and service providers, including their selection, contractual arrangements, performance, risk, compliance, and ongoing relationship management, so that externally provided products and services meet organisational requirements.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'capability-evolution', 'Stewarding capability evolution and maturity', 'assess, govern, and guide the evolution and maturity of organisational capabilities by establishing capability objectives, evaluating current capability performance and maturity, identifying gaps and improvement opportunities, defining evolutionary priorities, and monitoring progress toward the desired capability state.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'change-management', 'Managing engineering change', 'control proposed changes to engineering artefacts and engineering baselines by assessing their justification, impact, dependencies, risks, and consequences, obtaining appropriate authorisation, coordinating their implementation, and maintaining traceable records of the resulting state.', '11111111-1111-1111-1111-111111111111'),
  -- CR-087 — 3 codes added 2026-09-03, surfaced reviewing whether AI Platform/
  -- Embedded Software/Data Platform had any genuine existing-capability fit
  -- (none did — the tier above is about the engineering ORGANISATION's own
  -- AI-native operating maturity, not about building an AI/ML, firmware, or
  -- data-pipeline PRODUCT). Each ties to its own real, 1:1 Service Definition
  -- (migration 161), same discipline as every capability above.
  ('capability-name', 'training-and-evaluating-models', 'Training and evaluating models', 'prepare training/evaluation data, train or fine-tune a model against a defined objective, and evaluate its quality, bias, and performance against acceptance criteria before it is fit to serve — a materially different discipline from constructing general-purpose software components.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'engineering-embedded-firmware', 'Engineering embedded firmware', 'build and verify firmware against a hardware-constrained target — memory, timing, interrupt, and power budgets a general-purpose runtime does not have — confirming it behaves correctly on the real or simulated hardware it will ship on.', '11111111-1111-1111-1111-111111111111'),
  ('capability-name', 'engineering-data-pipelines', 'Engineering data pipelines', 'design, build, and operate the ingestion, transformation, and quality-assurance pipelines that move and shape data reliably — a distinct discipline from constructing general application components.', '11111111-1111-1111-1111-111111111111')
ON CONFLICT (concept_type, code, tenant_id) DO NOTHING;
