-- CR-086/Ch.11 follow-on — service_definitions.service_level becomes a real
-- structured JSONB array instead of free-text, one object per measurable
-- expectation: {code, label, target_level, target, units} (owner-specified
-- shape, e.g. {code: "ambiguity-free", label: "Percent unambiguous
-- requirements", target_level: "minimum", target: 60, units: "percent"}).
--
-- The source CSV (design/fragments/services.csv) only ever named the quality
-- attribute (e.g. "ambiguity-free", "detection latency") — it never specified
-- an actual number. target_level/target/units below are a reasoned FIRST-PASS
-- baseline, not owner-specified values: percentage-style attributes (complete-
-- ness/coverage/consistency/accuracy/traceability) default to minimum 90%
-- (100% where the phrase itself says "no X"/"full X"/"every X"); "no X"/
-- "zero X" defect-style phrases become maximum 0 (count); latency/timeliness
-- phrases become a plausible maximum duration; rate-of-failure phrases (false-
-- positive/negative) become maximum 5%; purely qualitative, non-numeric
-- attributes (explainability, reviewer independence, resilience, etc.) become
-- exact 100% ("must always hold"). Adjust freely — these exist so the column
-- has real, structurally valid content, not because the target numbers
-- themselves are authoritative.

ALTER TABLE service_definitions ALTER COLUMN service_level DROP DEFAULT;
ALTER TABLE service_definitions ALTER COLUMN service_level TYPE JSONB USING '[]'::jsonb;
ALTER TABLE service_definitions ALTER COLUMN service_level SET DEFAULT '[]'::jsonb;
ALTER TABLE service_definitions ALTER COLUMN service_level SET NOT NULL;

-- Authoring schema: serviceLevel becomes a real nested-list field, same
-- {label, target}-style mechanism migration 114 already gave Pack's own
-- contributionServices[].serviceLevel[] — just with the two extra fields
-- (code, target_level, units) this table's own richer shape needs.
UPDATE schema_definitions
   SET schema = jsonb_set(
     schema,
     '{properties,serviceLevel}',
     '{
       "type": "array",
       "x-help": "The measurable expectations this Service declares for its own delivery (Ch.11 §8) — as many rows as needed.",
       "items": {
         "type": "object",
         "required": ["code", "label", "target_level", "target", "units"],
         "x-property-order": ["code", "label", "target_level", "target", "units"],
         "properties": {
           "code": {"type": "string", "x-help": "A short, stable identifier for this expectation, e.g. \"ambiguity-free\"."},
           "label": {"type": "string", "x-help": "Human-readable description, e.g. \"Percent unambiguous requirements\"."},
           "target_level": {"type": "string", "enum": ["minimum", "maximum", "exact"], "x-help": "Whether target is a floor, a ceiling, or must be met exactly."},
           "target": {"type": "number", "x-help": "The numeric target, e.g. 60."},
           "units": {"type": "string", "x-help": "The unit target is measured in, e.g. \"percent\", \"hours\", \"count\"."}
         }
       }
     }'::jsonb
   )
 WHERE entity_kind = 'Service' AND version = 1;

UPDATE service_definitions SET service_level = '[{"code": "completeness", "label": "Completeness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "stakeholder-coverage", "label": "Stakeholder coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "ambiguity-free", "label": "Ambiguity-free", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "completeness", "label": "Completeness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "stakeholder-coverage", "label": "Stakeholder coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "ambiguity-free", "label": "Ambiguity-free", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'requirements-elicitation';
UPDATE service_definitions SET service_level = '[{"code": "consistency", "label": "Consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "terminological-precision", "label": "Terminological precision", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "consistency", "label": "Consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "terminological-precision", "label": "Terminological precision", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'understanding-business-domain';
UPDATE service_definitions SET service_level = '[{"code": "completeness-of-decomposition", "label": "Completeness of decomposition", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "no-unresolved-conflict-left-silent", "label": "No unresolved conflict left silent", "target_level": "maximum", "target": 0, "units": "count"}, {"code": "traceability-from-each-detailed-requirement-back-to-its-source-statement", "label": "Traceability from each detailed requirement back to its source statement", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "consistent-categorisation", "label": "Consistent categorisation", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "completeness-of-decomposition", "label": "Completeness of decomposition", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "no-unresolved-conflict-left-silent", "label": "No unresolved conflict left silent", "target_level": "maximum", "target": 0, "units": "count"}, {"code": "traceability-from-each-detailed-requirement-back-to-its-source-statement", "label": "Traceability from each detailed requirement back to its source statement", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "consistent-categorisation", "label": "Consistent categorisation", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'requirements-analysis';
UPDATE service_definitions SET service_level = '[{"code": "traceability", "label": "Traceability", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "stakeholder-sign-off", "label": "Stakeholder sign-off", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "no-unresolved-conflict", "label": "No unresolved conflict", "target_level": "maximum", "target": 0, "units": "count"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "traceability", "label": "Traceability", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "stakeholder-sign-off", "label": "Stakeholder sign-off", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "no-unresolved-conflict", "label": "No unresolved conflict", "target_level": "maximum", "target": 0, "units": "count"}]'::jsonb) WHERE capability_code = 'requirements-validation';
UPDATE service_definitions SET service_level = '[{"code": "internal-consistency", "label": "Internal consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "completeness-against-requirements", "label": "Completeness against requirements", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "internal-consistency", "label": "Internal consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "completeness-against-requirements", "label": "Completeness against requirements", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'modelling-complex-systems';
UPDATE service_definitions SET service_level = '[{"code": "compliance-with-architecture-principle", "label": "Compliance with architecture principle", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "complete-reasoning", "label": "Complete reasoning", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "full-traceability", "label": "Full traceability", "target_level": "minimum", "target": 100, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "compliance-with-architecture-principle", "label": "Compliance with architecture principle", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "complete-reasoning", "label": "Complete reasoning", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "full-traceability", "label": "Full traceability", "target_level": "minimum", "target": 100, "units": "percent"}]'::jsonb) WHERE capability_code = 'architecture-design';
UPDATE service_definitions SET service_level = '[{"code": "functional-correctness", "label": "Functional correctness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "adherence-to-standard", "label": "Adherence to standard", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "maintainability", "label": "Maintainability", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "functional-correctness", "label": "Functional correctness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "adherence-to-standard", "label": "Adherence to standard", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "maintainability", "label": "Maintainability", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'software-construction';
UPDATE service_definitions SET service_level = '[{"code": "internal-consistency", "label": "Internal consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "conformance-to-the-architectural-constraints-it-was-handed", "label": "Conformance to the architectural constraints it was handed", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "completeness-no-significant-design-decision-left-for-the-developer-to-invent-unspecified", "label": "Completeness (no significant design decision left for the developer to invent unspecified)", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "testability-of-the-resulting-structure", "label": "Testability of the resulting structure", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "internal-consistency", "label": "Internal consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "conformance-to-the-architectural-constraints-it-was-handed", "label": "Conformance to the architectural constraints it was handed", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "completeness-no-significant-design-decision-left-for-the-developer-to-invent-unspecified", "label": "Completeness (no significant design decision left for the developer to invent unspecified)", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "testability-of-the-resulting-structure", "label": "Testability of the resulting structure", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'software-design';
UPDATE service_definitions SET service_level = '[{"code": "consistency", "label": "Consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "no-untracked-drift", "label": "No untracked drift", "target_level": "maximum", "target": 0, "units": "count"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "consistency", "label": "Consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "no-untracked-drift", "label": "No untracked drift", "target_level": "maximum", "target": 0, "units": "count"}]'::jsonb) WHERE capability_code = 'engineering-configuration';
UPDATE service_definitions SET service_level = '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "defect-detection-effectiveness", "label": "Defect-detection effectiveness", "target_level": "minimum", "target": 85, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "defect-detection-effectiveness", "label": "Defect-detection effectiveness", "target_level": "minimum", "target": 85, "units": "percent"}]'::jsonb) WHERE capability_code = 'software-validation';
UPDATE service_definitions SET service_level = '[{"code": "currency", "label": "Currency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "completeness", "label": "Completeness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "clarity", "label": "Clarity", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "currency", "label": "Currency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "completeness", "label": "Completeness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "clarity", "label": "Clarity", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'engineering-documentation';
UPDATE service_definitions SET service_level = '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "false-negative-minimisation", "label": "False-negative minimisation", "target_level": "maximum", "target": 5, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "false-negative-minimisation", "label": "False-negative minimisation", "target_level": "maximum", "target": 5, "units": "percent"}]'::jsonb) WHERE capability_code = 'protect-organisational-assets';
UPDATE service_definitions SET service_level = '[{"code": "consistency", "label": "Consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "explainability", "label": "Explainability", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "consistency", "label": "Consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "explainability", "label": "Explainability", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb) WHERE capability_code = 'governing-engineering-decisions';
UPDATE service_definitions SET service_level = '[{"code": "risk-adjusted-go-no-go-accuracy", "label": "Risk-adjusted go/no-go accuracy", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "risk-adjusted-go-no-go-accuracy", "label": "Risk-adjusted go/no-go accuracy", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'software-release';
UPDATE service_definitions SET service_level = '[{"code": "uptime", "label": "Uptime", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "mean-time-to-detect", "label": "Mean-time-to-detect", "target_level": "maximum", "target": 4, "units": "hours"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "uptime", "label": "Uptime", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "mean-time-to-detect", "label": "Mean-time-to-detect", "target_level": "maximum", "target": 4, "units": "hours"}]'::jsonb) WHERE capability_code = 'operating-production-systems';
UPDATE service_definitions SET service_level = '[{"code": "accuracy", "label": "Accuracy", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "provenance-completeness", "label": "Provenance completeness", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "accuracy", "label": "Accuracy", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "provenance-completeness", "label": "Provenance completeness", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'recovering-organisational-knowledge';
UPDATE service_definitions SET service_level = '[{"code": "actionability", "label": "Actionability", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "timeliness", "label": "Timeliness", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "actionability", "label": "Actionability", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "timeliness", "label": "Timeliness", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb) WHERE capability_code = 'learning';
UPDATE service_definitions SET service_level = '[{"code": "adoption-rate", "label": "Adoption rate", "target_level": "minimum", "target": 85, "units": "percent"}, {"code": "defect-reduction-impact", "label": "Defect-reduction impact", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "adoption-rate", "label": "Adoption rate", "target_level": "minimum", "target": 85, "units": "percent"}, {"code": "defect-reduction-impact", "label": "Defect-reduction impact", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'engineering-practice-improvement';
UPDATE service_definitions SET service_level = '[{"code": "responsiveness", "label": "Responsiveness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "accuracy-of-gap-identification", "label": "Accuracy of gap identification", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "responsiveness", "label": "Responsiveness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "accuracy-of-gap-identification", "label": "Accuracy of gap identification", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'adapting-business-needs';
UPDATE service_definitions SET service_level = '[{"code": "latency-near-zero", "label": "Latency (near-zero)", "target_level": "maximum", "target": 24, "units": "hours"}, {"code": "false-positive-rate", "label": "False-positive rate", "target_level": "maximum", "target": 5, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "latency-near-zero", "label": "Latency (near-zero)", "target_level": "maximum", "target": 24, "units": "hours"}, {"code": "false-positive-rate", "label": "False-positive rate", "target_level": "maximum", "target": 5, "units": "percent"}]'::jsonb) WHERE capability_code = 'continuous-architectural-analysis';
UPDATE service_definitions SET service_level = '[{"code": "currency-zero-lag", "label": "Currency (zero lag)", "target_level": "maximum", "target": 0, "units": "seconds"}, {"code": "accuracy", "label": "Accuracy", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "currency-zero-lag", "label": "Currency (zero lag)", "target_level": "maximum", "target": 0, "units": "seconds"}, {"code": "accuracy", "label": "Accuracy", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'real-time-organisational-documentation';
UPDATE service_definitions SET service_level = '[{"code": "completeness", "label": "Completeness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "no-orphaned-link", "label": "No orphaned link", "target_level": "maximum", "target": 0, "units": "count"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "completeness", "label": "Completeness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "no-orphaned-link", "label": "No orphaned link", "target_level": "maximum", "target": 0, "units": "count"}]'::jsonb) WHERE capability_code = 'automatic-traceability-generation';
UPDATE service_definitions SET service_level = '[{"code": "accuracy-against-ground-truth-where-verifiable", "label": "Accuracy against ground truth where verifiable", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "accuracy-against-ground-truth-where-verifiable", "label": "Accuracy against ground truth where verifiable", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'legacy-modernisation';
UPDATE service_definitions SET service_level = '[{"code": "zero-lag-detection", "label": "Zero-lag detection", "target_level": "maximum", "target": 0, "units": "seconds"}, {"code": "coverage-of-all-applicable-frameworks", "label": "Coverage of all applicable frameworks", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "zero-lag-detection", "label": "Zero-lag detection", "target_level": "maximum", "target": 0, "units": "seconds"}, {"code": "coverage-of-all-applicable-frameworks", "label": "Coverage of all applicable frameworks", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'continuous-compliance-verification';
UPDATE service_definitions SET service_level = '[{"code": "completeness-of-rationale-chain", "label": "Completeness of rationale chain", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "completeness-of-rationale-chain", "label": "Completeness of rationale chain", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'engineering-decision-explainability';
UPDATE service_definitions SET service_level = '[{"code": "consistency-with-prior-precedent", "label": "Consistency with prior precedent", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "evidentiary-support", "label": "Evidentiary support", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "consistency-with-prior-precedent", "label": "Consistency with prior precedent", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "evidentiary-support", "label": "Evidentiary support", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb) WHERE capability_code = 'evidence-based-organisational-reasoning';
UPDATE service_definitions SET service_level = '[{"code": "zero-lag-detection-of-newly-introduced-conflict", "label": "Zero-lag detection of newly introduced conflict", "target_level": "maximum", "target": 0, "units": "seconds"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "zero-lag-detection-of-newly-introduced-conflict", "label": "Zero-lag detection of newly introduced conflict", "target_level": "maximum", "target": 0, "units": "seconds"}]'::jsonb) WHERE capability_code = 'continuous-requirements-validation';
UPDATE service_definitions SET service_level = '[{"code": "predictive-accuracy-calibrated-against-outcomes", "label": "Predictive accuracy (calibrated against outcomes)", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "predictive-accuracy-calibrated-against-outcomes", "label": "Predictive accuracy (calibrated against outcomes)", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'predictive-engineering-risk-assessment';
UPDATE service_definitions SET service_level = '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "latency", "label": "Latency", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "latency", "label": "Latency", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb) WHERE capability_code = 'continuous-quality-assurance';
UPDATE service_definitions SET service_level = '[{"code": "generalisability", "label": "Generalisability", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "non-contradiction", "label": "Non-contradiction", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "generalisability", "label": "Generalisability", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "non-contradiction", "label": "Non-contradiction", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb) WHERE capability_code = 'organisational-memory-synthesis';
UPDATE service_definitions SET service_level = '[{"code": "cycle-time-between-evidence-and-improvement", "label": "Cycle time between evidence and improvement", "target_level": "maximum", "target": 4, "units": "hours"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "cycle-time-between-evidence-and-improvement", "label": "Cycle time between evidence and improvement", "target_level": "maximum", "target": 4, "units": "hours"}]'::jsonb) WHERE capability_code = 'continuous-organisational-learning';
UPDATE service_definitions SET service_level = '[{"code": "measurable-performance-delta", "label": "Measurable performance delta", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "non-regression", "label": "Non-regression", "target_level": "maximum", "target": 0, "units": "count"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "measurable-performance-delta", "label": "Measurable performance delta", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "non-regression", "label": "Non-regression", "target_level": "maximum", "target": 0, "units": "count"}]'::jsonb) WHERE capability_code = 'autonomous-capability-optimisation';
UPDATE service_definitions SET service_level = '[{"code": "completeness-of-affected-entity-discovery", "label": "Completeness of affected-entity discovery", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "completeness-of-affected-entity-discovery", "label": "Completeness of affected-entity discovery", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'enterprise-wide-engineering-impact-analysis';
UPDATE service_definitions SET service_level = '[{"code": "currency", "label": "Currency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "conflict-detection", "label": "Conflict detection", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "currency", "label": "Currency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "conflict-detection", "label": "Conflict detection", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'continuous-stakeholder-intent-reconciliation';
UPDATE service_definitions SET service_level = '[{"code": "detection-latency", "label": "Detection latency", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "detection-latency", "label": "Detection latency", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb) WHERE capability_code = 'continuous-domain-model-drift-detection';
UPDATE service_definitions SET service_level = '[{"code": "lead-time-before-actual-failure", "label": "Lead time before actual failure", "target_level": "minimum", "target": 14, "units": "days"}, {"code": "accuracy", "label": "Accuracy", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "lead-time-before-actual-failure", "label": "Lead time before actual failure", "target_level": "minimum", "target": 14, "units": "days"}, {"code": "accuracy", "label": "Accuracy", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'predictive-architectural-obsolescence-detection';
UPDATE service_definitions SET service_level = '[{"code": "cross-system-coverage", "label": "Cross-system coverage", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "cross-system-coverage", "label": "Cross-system coverage", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'cross-system-structural-pattern-recognition';
UPDATE service_definitions SET service_level = '[{"code": "precision-no-incorrect-propagation", "label": "Precision (no incorrect propagation)", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "precision-no-incorrect-propagation", "label": "Precision (no incorrect propagation)", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'cross-codebase-pattern-propagation';
UPDATE service_definitions SET service_level = '[{"code": "detection-latency", "label": "Detection latency", "target_level": "maximum", "target": 24, "units": "hours"}, {"code": "coverage-across-environments", "label": "Coverage across environments", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "detection-latency", "label": "Detection latency", "target_level": "maximum", "target": 24, "units": "hours"}, {"code": "coverage-across-environments", "label": "Coverage across environments", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'continuous-configuration-drift-detection';
UPDATE service_definitions SET service_level = '[{"code": "predictive-precision", "label": "Predictive precision", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "predictive-precision", "label": "Predictive precision", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'predictive-test-coverage-gap-detection';
UPDATE service_definitions SET service_level = '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "zero-lag", "label": "Zero-lag", "target_level": "maximum", "target": 0, "units": "seconds"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "zero-lag", "label": "Zero-lag", "target_level": "maximum", "target": 0, "units": "seconds"}]'::jsonb) WHERE capability_code = 'continuous-vulnerability-posture-assessment';
UPDATE service_definitions SET service_level = '[{"code": "time-to-check-after-new-pattern-publication", "label": "Time-to-check after new pattern publication", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "time-to-check-after-new-pattern-publication", "label": "Time-to-check after new pattern publication", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb) WHERE capability_code = 'predictive-threat-pattern-anticipation';
UPDATE service_definitions SET service_level = '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "false-positive-rate", "label": "False-positive rate", "target_level": "maximum", "target": 5, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "false-positive-rate", "label": "False-positive rate", "target_level": "maximum", "target": 5, "units": "percent"}]'::jsonb) WHERE capability_code = 'continuous-policy-conflict-detection';
UPDATE service_definitions SET service_level = '[{"code": "calibration-accuracy", "label": "Calibration accuracy", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "calibration-accuracy", "label": "Calibration accuracy", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'continuous-release-risk-management';
UPDATE service_definitions SET service_level = '[{"code": "lead-time", "label": "Lead time", "target_level": "maximum", "target": 24, "units": "hours"}, {"code": "false-positive-rate", "label": "False-positive rate", "target_level": "maximum", "target": 5, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "lead-time", "label": "Lead time", "target_level": "maximum", "target": 24, "units": "hours"}, {"code": "false-positive-rate", "label": "False-positive rate", "target_level": "maximum", "target": 5, "units": "percent"}]'::jsonb) WHERE capability_code = 'predictive-incident-anticipation';
UPDATE service_definitions SET service_level = '[{"code": "accuracy", "label": "Accuracy", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "completeness", "label": "Completeness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "time-to-synthesis", "label": "Time-to-synthesis", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "accuracy", "label": "Accuracy", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "completeness", "label": "Completeness", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "time-to-synthesis", "label": "Time-to-synthesis", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb) WHERE capability_code = 'autonomous-root-cause-synthesis';
UPDATE service_definitions SET service_level = '[{"code": "evidentiary-grounding", "label": "Evidentiary grounding", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "adoption-rate-post-publication", "label": "Adoption rate post-publication", "target_level": "minimum", "target": 85, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "evidentiary-grounding", "label": "Evidentiary grounding", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "adoption-rate-post-publication", "label": "Adoption rate post-publication", "target_level": "minimum", "target": 85, "units": "percent"}]'::jsonb) WHERE capability_code = 'autonomous-standard-synthesis';
UPDATE service_definitions SET service_level = '[{"code": "comparability", "label": "Comparability", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "tenant-isolation-compliance", "label": "Tenant-isolation compliance", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "comparability", "label": "Comparability", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "tenant-isolation-compliance", "label": "Tenant-isolation compliance", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb) WHERE capability_code = 'cross-organisational-capability-benchmarking';
UPDATE service_definitions SET service_level = '[{"code": "detection-latency", "label": "Detection latency", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "detection-latency", "label": "Detection latency", "target_level": "maximum", "target": 24, "units": "hours"}]'::jsonb) WHERE capability_code = 'continuous-objective-alignment-monitoring';
UPDATE service_definitions SET service_level = '[{"code": "fitness-of-approach-to-context-right-sized-neither-over-nor-under-specified-for-the-engagement", "label": "Fitness of approach to context (right-sized, neither over- nor under-specified for the engagement)", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "completeness-of-governance-checkpoints", "label": "Completeness of governance checkpoints", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "fitness-of-approach-to-context-right-sized-neither-over-nor-under-specified-for-the-engagement", "label": "Fitness of approach to context (right-sized, neither over- nor under-specified for the engagement)", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "completeness-of-governance-checkpoints", "label": "Completeness of governance checkpoints", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'business-analysis-approach';
UPDATE service_definitions SET service_level = '[{"code": "consistent-application-of-ranking-criteria", "label": "Consistent application of ranking criteria", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "documented-rationale-for-every-ranking", "label": "Documented rationale for every ranking", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "stakeholder-agreement", "label": "Stakeholder agreement", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "consistent-application-of-ranking-criteria", "label": "Consistent application of ranking criteria", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "documented-rationale-for-every-ranking", "label": "Documented rationale for every ranking", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "stakeholder-agreement", "label": "Stakeholder agreement", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb) WHERE capability_code = 'requirements-prioritising';
UPDATE service_definitions SET service_level = '[{"code": "completeness-of-options-considered", "label": "Completeness of options considered", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "transparency-and-defensibility-of-comparison-criteria", "label": "Transparency and defensibility of comparison criteria", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "full-traceability-from-recommendation-back-to-requirement", "label": "Full traceability from recommendation back to requirement", "target_level": "minimum", "target": 100, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "completeness-of-options-considered", "label": "Completeness of options considered", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "transparency-and-defensibility-of-comparison-criteria", "label": "Transparency and defensibility of comparison criteria", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "full-traceability-from-recommendation-back-to-requirement", "label": "Full traceability from recommendation back to requirement", "target_level": "minimum", "target": 100, "units": "percent"}]'::jsonb) WHERE capability_code = 'solution-options';
UPDATE service_definitions SET service_level = '[{"code": "interface-conformance", "label": "Interface conformance", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "absence-of-integration-defects", "label": "Absence of integration defects", "target_level": "maximum", "target": 0, "units": "count"}, {"code": "completeness", "label": "Completeness", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "interface-conformance", "label": "Interface conformance", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "absence-of-integration-defects", "label": "Absence of integration defects", "target_level": "maximum", "target": 0, "units": "count"}, {"code": "completeness", "label": "Completeness", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'integrating-constructed-components';
UPDATE service_definitions SET service_level = '[{"code": "fitness-for-purpose-accuracy", "label": "Fitness-for-purpose accuracy", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "security-and-quality-vetting-of-the-reused-asset", "label": "Security and quality vetting of the reused asset", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "fitness-for-purpose-accuracy", "label": "Fitness-for-purpose accuracy", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "security-and-quality-vetting-of-the-reused-asset", "label": "Security and quality vetting of the reused asset", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb) WHERE capability_code = 'engineering-assets-reuse';
UPDATE service_definitions SET service_level = '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "reviewer-independence-from-the-artefact-s-producer", "label": "Reviewer independence from the artefact''s producer", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "consistency-of-applied-standard", "label": "Consistency of applied standard", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "coverage", "label": "Coverage", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "reviewer-independence-from-the-artefact-s-producer", "label": "Reviewer independence from the artefact''s producer", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "consistency-of-applied-standard", "label": "Consistency of applied standard", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'engineering-work-review';
UPDATE service_definitions SET service_level = '[{"code": "closure-rate", "label": "Closure rate", "target_level": "minimum", "target": 85, "units": "percent"}, {"code": "recurrence-rate-after-closure", "label": "Recurrence rate after closure", "target_level": "minimum", "target": 85, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "closure-rate", "label": "Closure rate", "target_level": "minimum", "target": 85, "units": "percent"}, {"code": "recurrence-rate-after-closure", "label": "Recurrence rate after closure", "target_level": "minimum", "target": 85, "units": "percent"}]'::jsonb) WHERE capability_code = 'corrective-actions';
UPDATE service_definitions SET service_level = '[{"code": "triage-consistency", "label": "Triage consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "resolution-timeliness-relative-to-severity", "label": "Resolution timeliness relative to severity", "target_level": "maximum", "target": 48, "units": "hours"}, {"code": "no-defect-left-untracked", "label": "No defect left untracked", "target_level": "maximum", "target": 0, "units": "count"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "triage-consistency", "label": "Triage consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "resolution-timeliness-relative-to-severity", "label": "Resolution timeliness relative to severity", "target_level": "maximum", "target": 48, "units": "hours"}, {"code": "no-defect-left-untracked", "label": "No defect left untracked", "target_level": "maximum", "target": 0, "units": "count"}]'::jsonb) WHERE capability_code = 'defect-management';
UPDATE service_definitions SET service_level = '[{"code": "contract-compliance-rate", "label": "Contract-compliance rate", "target_level": "minimum", "target": 85, "units": "percent"}, {"code": "vendor-performance-against-sla", "label": "Vendor performance against SLA", "target_level": "minimum", "target": 85, "units": "percent"}, {"code": "completeness-of-risk-assessment", "label": "Completeness of risk assessment", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "contract-compliance-rate", "label": "Contract-compliance rate", "target_level": "minimum", "target": 85, "units": "percent"}, {"code": "vendor-performance-against-sla", "label": "Vendor performance against SLA", "target_level": "minimum", "target": 85, "units": "percent"}, {"code": "completeness-of-risk-assessment", "label": "Completeness of risk assessment", "target_level": "minimum", "target": 90, "units": "percent"}]'::jsonb) WHERE capability_code = 'vendor-supplier-management';
UPDATE service_definitions SET service_level = '[{"code": "the-five-dimensions-6-13-names-for-capability-measurement-itself-outcome-consistency", "label": "The five dimensions \u00a76.13 names for capability measurement itself \u2014 outcome consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "resilience", "label": "Resilience", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "adaptability", "label": "Adaptability", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "organisational-learning", "label": "Organisational learning", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "alignment-with-organisational-objective", "label": "Alignment with organisational objective", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "the-five-dimensions-6-13-names-for-capability-measurement-itself-outcome-consistency", "label": "The five dimensions \u00a76.13 names for capability measurement itself \u2014 outcome consistency", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "resilience", "label": "Resilience", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "adaptability", "label": "Adaptability", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "organisational-learning", "label": "Organisational learning", "target_level": "exact", "target": 100, "units": "percent"}, {"code": "alignment-with-organisational-objective", "label": "Alignment with organisational objective", "target_level": "exact", "target": 100, "units": "percent"}]'::jsonb) WHERE capability_code = 'capability-evolution';
UPDATE service_definitions SET service_level = '[{"code": "consistency-of-risk-assessment-across-similar-changes", "label": "Consistency of risk assessment across similar changes", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "accuracy-of-conflict-detection-no-two-conflicting-changes-approved-into-the-same-window", "label": "Accuracy of conflict detection (no two conflicting changes approved into the same window)", "target_level": "maximum", "target": 0, "units": "count"}, {"code": "decision-timeliness-relative-to-the-change-s-urgency", "label": "Decision timeliness relative to the change''s urgency", "target_level": "maximum", "target": 48, "units": "hours"}]'::jsonb, draft_content = jsonb_set(draft_content, '{serviceLevel}', '[{"code": "consistency-of-risk-assessment-across-similar-changes", "label": "Consistency of risk assessment across similar changes", "target_level": "minimum", "target": 90, "units": "percent"}, {"code": "accuracy-of-conflict-detection-no-two-conflicting-changes-approved-into-the-same-window", "label": "Accuracy of conflict detection (no two conflicting changes approved into the same window)", "target_level": "maximum", "target": 0, "units": "count"}, {"code": "decision-timeliness-relative-to-the-change-s-urgency", "label": "Decision timeliness relative to the change''s urgency", "target_level": "maximum", "target": 48, "units": "hours"}]'::jsonb) WHERE capability_code = 'change-management';
