-- CR-086/Ch.11 follow-on (owner, 2026-09-03) — service_definitions.inputs/
-- outputs stop being free text and become arrays of `deliverable-name`
-- Ontology codes (migration 048's now-62-code vocabulary), the same
-- referential-multi-select shape `consumers` already has against
-- capability-name (migration 156).
--
-- Every one of the 60 rows' original inputs/outputs text was reviewed phrase
-- by phrase. Roughly half of it isn't deliverable-shaped at all — live
-- signals/telemetry ("continuous telemetry", "every artefact/model change"),
-- status/alert outputs ("drift alert", "live posture status"), entities
-- ("active Objective"), or actors/raw comms ("stakeholder access", "meetings,
-- tickets, support conversations, email"). Owner: "move the non deliverables
-- into the policy column. so, inputs and outputs have only ontology
-- deliverable-name" — so every phrase that isn't a genuine deliverable is
-- folded into `governance` instead of being dropped or forced into a
-- deliverable-name code it doesn't fit. A further 8 phrases turned out to be
-- genuine deliverable-shaped gaps in the vocabulary (System Model, Decision
-- Record, Configuration Baseline Record, Confidence Assessment, Operational
-- Intelligence Report, Benchmark Report, Vendor Performance Record,
-- Capability Metrics/Evolution Roadmap) and were added to migration 048
-- rather than pushed to governance.
--
-- Consequence, expected and confirmed with the owner before writing this:
-- 9 of 60 rows end up with EMPTY inputs and outputs (entirely
-- signal/status-driven services — e.g. persistent-compliance-service,
-- stakeholder-intent-reconciliation-service) — nothing is lost, the
-- descriptive content lives in governance instead.

ALTER TABLE service_definitions ALTER COLUMN inputs DROP DEFAULT;
ALTER TABLE service_definitions ALTER COLUMN inputs TYPE TEXT[] USING '{}'::text[];
ALTER TABLE service_definitions ALTER COLUMN inputs SET DEFAULT '{}'::text[];
ALTER TABLE service_definitions ALTER COLUMN inputs SET NOT NULL;

ALTER TABLE service_definitions ALTER COLUMN outputs DROP DEFAULT;
ALTER TABLE service_definitions ALTER COLUMN outputs TYPE TEXT[] USING '{}'::text[];
ALTER TABLE service_definitions ALTER COLUMN outputs SET DEFAULT '{}'::text[];
ALTER TABLE service_definitions ALTER COLUMN outputs SET NOT NULL;

-- Authoring schema: inputs/outputs become referential-multi-select fields
-- against deliverable-name, the same mechanism migration 156 gave `consumers`
-- against capability-name.
UPDATE schema_definitions
   SET schema = jsonb_set(
                  jsonb_set(
                    jsonb_set(
                      jsonb_set(
                        jsonb_set(
                          jsonb_set(
                            schema,
                            '{properties,inputs,x-widget}', '"referential-multi-select"'::jsonb
                          ),
                          '{properties,inputs,x-ontology}', 'true'::jsonb
                        ),
                        '{properties,inputs,x-referential-source}', '"deliverable-name"'::jsonb
                      ),
                      '{properties,outputs,x-widget}', '"referential-multi-select"'::jsonb
                    ),
                    '{properties,outputs,x-ontology}', 'true'::jsonb
                  ),
                  '{properties,outputs,x-referential-source}', '"deliverable-name"'::jsonb
                )
 WHERE entity_kind = 'Service' AND version = 1;

UPDATE service_definitions SET inputs = ARRAY['domain-model','vision']::text[], outputs = ARRAY['requirements-backlog']::text[], governance = 'requirements-management policy; also draws on stakeholder access', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['domain-model','vision']::text[])), '{outputs}', to_jsonb(ARRAY['requirements-backlog']::text[])), '{governance}', to_jsonb('requirements-management policy; also draws on stakeholder access'::text)) WHERE code = 'requirements-discovery-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['domain-model']::text[], governance = 'Ontology Model policy; draws on business documentation, stakeholder interviews, and existing domain artefacts', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['domain-model']::text[])), '{governance}', to_jsonb('Ontology Model policy; draws on business documentation, stakeholder interviews, and existing domain artefacts'::text)) WHERE code = 'domain-model-service';

UPDATE service_definitions SET inputs = ARRAY['requirements-backlog']::text[], outputs = ARRAY['requirements-analysis-model']::text[], governance = 'requirements-management policy, decomposition and traceability standard; also draws on stakeholder context and constraints', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['requirements-backlog']::text[])), '{outputs}', to_jsonb(ARRAY['requirements-analysis-model']::text[])), '{governance}', to_jsonb('requirements-management policy, decomposition and traceability standard; also draws on stakeholder context and constraints'::text)) WHERE code = 'requirements-analysis-service';

UPDATE service_definitions SET inputs = ARRAY['requirements-analysis-model']::text[], outputs = ARRAY['requirements-specification']::text[], governance = 'change-control policy; also draws on acceptance criteria', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['requirements-analysis-model']::text[])), '{outputs}', to_jsonb(ARRAY['requirements-specification']::text[])), '{governance}', to_jsonb('change-control policy; also draws on acceptance criteria'::text)) WHERE code = 'requirement-validation-service';

UPDATE service_definitions SET inputs = ARRAY['requirements-specification','domain-model']::text[], outputs = ARRAY['system-model']::text[], governance = 'modelling standard; also draws on system/environment constraints', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['requirements-specification','domain-model']::text[])), '{outputs}', to_jsonb(ARRAY['system-model']::text[])), '{governance}', to_jsonb('modelling standard; also draws on system/environment constraints'::text)) WHERE code = 'system-model-service';

UPDATE service_definitions SET inputs = ARRAY['solution-options-analysis','requirements-specification','engineering-standard']::text[], outputs = ARRAY['architecture-decision-record','risk-assessment-report']::text[], governance = 'enterprise architecture policy, security standard, technology standard, regulatory obligation; also draws on the relevant architectural constraint; output also folds in a recommendation alongside the architectural decision record', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['solution-options-analysis','requirements-specification','engineering-standard']::text[])), '{outputs}', to_jsonb(ARRAY['architecture-decision-record','risk-assessment-report']::text[])), '{governance}', to_jsonb('enterprise architecture policy, security standard, technology standard, regulatory obligation; also draws on the relevant architectural constraint; output also folds in a recommendation alongside the architectural decision record'::text)) WHERE code = 'architectural-review-service';

UPDATE service_definitions SET inputs = ARRAY['solution-architecture-document','engineering-standard']::text[], outputs = ARRAY['source-code']::text[], draft_content = jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['solution-architecture-document','engineering-standard']::text[])), '{outputs}', to_jsonb(ARRAY['source-code']::text[])) WHERE code = 'software-implementation-service';

UPDATE service_definitions SET inputs = ARRAY['solution-architecture-document','requirements-analysis-model']::text[], outputs = ARRAY['detailed-design-specification']::text[], draft_content = jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['solution-architecture-document','requirements-analysis-model']::text[])), '{outputs}', to_jsonb(ARRAY['detailed-design-specification']::text[])) WHERE code = 'detailed-design-service';

UPDATE service_definitions SET inputs = ARRAY['change-request']::text[], outputs = ARRAY['configuration-baseline-record']::text[], governance = 'configuration-management policy; also draws on tracked artefact versions', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['change-request']::text[])), '{outputs}', to_jsonb(ARRAY['configuration-baseline-record']::text[])), '{governance}', to_jsonb('configuration-management policy; also draws on tracked artefact versions'::text)) WHERE code = 'baseline-management-service';

UPDATE service_definitions SET inputs = ARRAY['source-code','requirements-specification','engineering-standard']::text[], outputs = ARRAY['test-report-results','defect-log','confidence-assessment']::text[], draft_content = jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['source-code','requirements-specification','engineering-standard']::text[])), '{outputs}', to_jsonb(ARRAY['test-report-results','defect-log','confidence-assessment']::text[])) WHERE code = 'quality-assurance-service';

UPDATE service_definitions SET inputs = ARRAY['architecture-decision-record','source-code','requirements-specification']::text[], outputs = ARRAY['user-technical-documentation']::text[], draft_content = jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['architecture-decision-record','source-code','requirements-specification']::text[])), '{outputs}', to_jsonb(ARRAY['user-technical-documentation']::text[])) WHERE code = 'technical-documentation-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['security-assessment-report']::text[], governance = 'security policy, regulatory obligation; also draws on system artefacts and current threat intelligence; also produces a policy enforcement record', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['security-assessment-report']::text[])), '{governance}', to_jsonb('security policy, regulatory obligation; also draws on system artefacts and current threat intelligence; also produces a policy enforcement record'::text)) WHERE code = 'vulnerability-assessment-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['decision-record']::text[], governance = 'decision-governance policy; also draws on the proposed decision itself and the applicable policy it is evaluated against', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['decision-record']::text[])), '{governance}', to_jsonb('decision-governance policy; also draws on the proposed decision itself and the applicable policy it is evaluated against'::text)) WHERE code = 'decision-validation-service';

UPDATE service_definitions SET inputs = ARRAY['test-report-results','release-package']::text[], outputs = ARRAY['deployment-manifest']::text[], governance = 'release policy, change-control standard; also produces a release recommendation alongside the deployment coordination record', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['test-report-results','release-package']::text[])), '{outputs}', to_jsonb(ARRAY['deployment-manifest']::text[])), '{governance}', to_jsonb('release policy, change-control standard; also produces a release recommendation alongside the deployment coordination record'::text)) WHERE code = 'deployment-governance-service';

UPDATE service_definitions SET inputs = ARRAY['deployment-package','monitoring-alerting-configuration']::text[], outputs = ARRAY['incident-report-post-mortem','operational-intelligence-report']::text[], governance = 'SLA/operational policy; also produces live performance data', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['deployment-package','monitoring-alerting-configuration']::text[])), '{outputs}', to_jsonb(ARRAY['incident-report-post-mortem','operational-intelligence-report']::text[])), '{governance}', to_jsonb('SLA/operational policy; also produces live performance data'::text)) WHERE code = 'availability-assurance-service';

UPDATE service_definitions SET inputs = ARRAY['source-code']::text[], outputs = ARRAY['knowledge-base-articles']::text[], governance = 'knowledge validation policy; also draws on legacy artefacts and historical decisions', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['source-code']::text[])), '{outputs}', to_jsonb(ARRAY['knowledge-base-articles']::text[])), '{governance}', to_jsonb('knowledge validation policy; also draws on legacy artefacts and historical decisions'::text)) WHERE code = 'knowledge-discovery-service';

UPDATE service_definitions SET inputs = ARRAY['incident-report-post-mortem']::text[], outputs = ARRAY['operational-intelligence-report','lessons-learned-report']::text[], governance = 'organisational-learning policy; also draws on live telemetry and operational evidence', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['incident-report-post-mortem']::text[])), '{outputs}', to_jsonb(ARRAY['operational-intelligence-report','lessons-learned-report']::text[])), '{governance}', to_jsonb('organisational-learning policy; also draws on live telemetry and operational evidence'::text)) WHERE code = 'operational-intelligence-service';

UPDATE service_definitions SET inputs = ARRAY['review-report']::text[], outputs = ARRAY['engineering-standard']::text[], governance = 'standards-governance policy; also draws on evidence from service delivery; output also includes a checklist and practice guidance alongside the revised standard', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['review-report']::text[])), '{outputs}', to_jsonb(ARRAY['engineering-standard']::text[])), '{governance}', to_jsonb('standards-governance policy; also draws on evidence from service delivery; output also includes a checklist and practice guidance alongside the revised standard'::text)) WHERE code = 'standard-refinement-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['capability-maturity-assessment']::text[], governance = 'strategic-governance policy; also draws on revised or superseded Objectives and market/business signal; also produces a realignment recommendation', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['capability-maturity-assessment']::text[])), '{governance}', to_jsonb('strategic-governance policy; also draws on revised or superseded Objectives and market/business signal; also produces a realignment recommendation'::text)) WHERE code = 'capability-realignment-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY[]::text[], governance = 'architecture policy; continuously monitors every artefact/model change; produces real-time conformance status and drift alerts', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('architecture policy; continuously monitors every artefact/model change; produces real-time conformance status and drift alerts'::text)) WHERE code = 'architectural-awareness-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['user-technical-documentation']::text[], governance = 'documentation standard; continuously monitors every artefact change', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['user-technical-documentation']::text[])), '{governance}', to_jsonb('documentation standard; continuously monitors every artefact change'::text)) WHERE code = 'continuous-documentation-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['traceability-matrix']::text[], governance = 'traceability policy; continuously monitors every artefact/decision change', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['traceability-matrix']::text[])), '{governance}', to_jsonb('traceability policy; continuously monitors every artefact/decision change'::text)) WHERE code = 'continuous-trace-awareness-service';

UPDATE service_definitions SET inputs = ARRAY['source-code']::text[], outputs = ARRAY['knowledge-base-articles']::text[], governance = 'knowledge validation policy; also draws on historical records and operational history', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['source-code']::text[])), '{outputs}', to_jsonb(ARRAY['knowledge-base-articles']::text[])), '{governance}', to_jsonb('knowledge validation policy; also draws on historical records and operational history'::text)) WHERE code = 'legacy-knowledge-reconstruction-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY[]::text[], governance = 'every active Compliance Pack''s policy; continuously monitors every architectural/implementation/deployment/operational event; produces continuous compliance status and violation alerts', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('every active Compliance Pack''s policy; continuously monitors every architectural/implementation/deployment/operational event; produces continuous compliance status and violation alerts'::text)) WHERE code = 'persistent-compliance-service';

UPDATE service_definitions SET inputs = ARRAY['decision-record']::text[], outputs = ARRAY[]::text[], governance = 'decision-governance policy; also draws on supporting evidence; produces an explainable decision trace', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['decision-record']::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('decision-governance policy; also draws on supporting evidence; produces an explainable decision trace'::text)) WHERE code = 'decision-rationale-service';

UPDATE service_definitions SET inputs = ARRAY['knowledge-base-articles']::text[], outputs = ARRAY[]::text[], governance = 'decision-governance policy; also draws on accumulated evidence; produces a reasoned recommendation', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['knowledge-base-articles']::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('decision-governance policy; also draws on accumulated evidence; produces a reasoned recommendation'::text)) WHERE code = 'organisational-reasoning-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY[]::text[], governance = 'requirements-management policy; continuously monitors every requirement change; produces a continuous validation status', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('requirements-management policy; continuously monitors every requirement change; produces a continuous validation status'::text)) WHERE code = 'continuous-requirement-conformance-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['risk-assessment-report']::text[], governance = 'risk-management policy; also draws on historical risk/outcome data and current engineering state', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['risk-assessment-report']::text[])), '{governance}', to_jsonb('risk-management policy; also draws on historical risk/outcome data and current engineering state'::text)) WHERE code = 'engineering-risk-forecast-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['confidence-assessment','defect-log']::text[], governance = 'quality policy; continuously monitors every code/test change', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['confidence-assessment','defect-log']::text[])), '{governance}', to_jsonb('quality policy; continuously monitors every code/test change'::text)) WHERE code = 'continuous-confidence-service';

UPDATE service_definitions SET inputs = ARRAY['knowledge-base-articles']::text[], outputs = ARRAY['knowledge-base-articles']::text[], draft_content = jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['knowledge-base-articles']::text[])), '{outputs}', to_jsonb(ARRAY['knowledge-base-articles']::text[])) WHERE code = 'cross-project-knowledge-synthesis-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY[]::text[], governance = 'organisational-learning policy; draws on evidence generated by every service interaction; produces a capability-improvement recommendation', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('organisational-learning policy; draws on evidence generated by every service interaction; produces a capability-improvement recommendation'::text)) WHERE code = 'continuous-learning-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY[]::text[], governance = 'capability-ownership policy; draws on capability performance evidence; produces an applied optimisation and improvement record', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('capability-ownership policy; draws on capability performance evidence; produces an applied optimisation and improvement record'::text)) WHERE code = 'capability-self-optimisation-service';

UPDATE service_definitions SET inputs = ARRAY['change-request','traceability-matrix']::text[], outputs = ARRAY['impact-analysis-report']::text[], draft_content = jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['change-request','traceability-matrix']::text[])), '{outputs}', to_jsonb(ARRAY['impact-analysis-report']::text[])) WHERE code = 'cross-enterprise-impact-analysis-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY[]::text[], governance = 'requirements policy; draws on meetings, tickets, support conversations, and email; produces a continuously reconciled intent baseline', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('requirements policy; draws on meetings, tickets, support conversations, and email; produces a continuously reconciled intent baseline'::text)) WHERE code = 'stakeholder-intent-reconciliation-service';

UPDATE service_definitions SET inputs = ARRAY['domain-model']::text[], outputs = ARRAY[]::text[], governance = 'Ontology policy; also draws on live business signal; produces a drift alert', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['domain-model']::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('Ontology policy; also draws on live business signal; produces a drift alert'::text)) WHERE code = 'domain-model-conformance-service';

UPDATE service_definitions SET inputs = ARRAY['solution-architecture-document']::text[], outputs = ARRAY[]::text[], governance = 'architecture policy; also draws on usage/load telemetry; produces an obsolescence forecast', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['solution-architecture-document']::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('architecture policy; also draws on usage/load telemetry; produces an obsolescence forecast'::text)) WHERE code = 'architectural-obsolescence-forecast-service';

UPDATE service_definitions SET inputs = ARRAY['solution-architecture-document']::text[], outputs = ARRAY['risk-assessment-report']::text[], draft_content = jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['solution-architecture-document']::text[])), '{outputs}', to_jsonb(ARRAY['risk-assessment-report']::text[])) WHERE code = 'cross-system-pattern-recognition-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY[]::text[], governance = 'change-control policy; draws on an applied fix and the codebase inventory; produces propagation candidates and applied propagations', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('change-control policy; draws on an applied fix and the codebase inventory; produces propagation candidates and applied propagations'::text)) WHERE code = 'fix-propagation-service';

UPDATE service_definitions SET inputs = ARRAY['configuration-files']::text[], outputs = ARRAY[]::text[], governance = 'configuration-management policy; also draws on live environment state; produces a drift alert and remediation recommendation', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['configuration-files']::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('configuration-management policy; also draws on live environment state; produces a drift alert and remediation recommendation'::text)) WHERE code = 'configuration-conformance-service';

UPDATE service_definitions SET inputs = ARRAY['defect-log','test-suite','solution-architecture-document']::text[], outputs = ARRAY[]::text[], governance = 'quality policy; produces a predicted coverage gap', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['defect-log','test-suite','solution-architecture-document']::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('quality policy; produces a predicted coverage gap'::text)) WHERE code = 'coverage-gap-forecast-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY[]::text[], governance = 'security policy; continuously monitors every code/infrastructure change; produces a live posture status', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('security policy; continuously monitors every code/infrastructure change; produces a live posture status'::text)) WHERE code = 'continuous-security-posture-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['security-assessment-report']::text[], governance = 'security policy; also draws on external threat intelligence and the internal system inventory', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['security-assessment-report']::text[])), '{governance}', to_jsonb('security policy; also draws on external threat intelligence and the internal system inventory'::text)) WHERE code = 'threat-anticipation-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['policy-conflict-report']::text[], governance = 'governance policy itself; draws on the full policy corpus', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['policy-conflict-report']::text[])), '{governance}', to_jsonb('governance policy itself; draws on the full policy corpus'::text)) WHERE code = 'policy-consistency-service';

UPDATE service_definitions SET inputs = ARRAY['release-package']::text[], outputs = ARRAY[]::text[], governance = 'release policy; also draws on the full history of prior release outcomes; produces a continuously updated risk score', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['release-package']::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('release policy; also draws on the full history of prior release outcomes; produces a continuously updated risk score'::text)) WHERE code = 'release-risk-forecast-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY[]::text[], governance = 'operational policy; continuously monitors telemetry; produces an anticipatory alert', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY[]::text[])), '{governance}', to_jsonb('operational policy; continuously monitors telemetry; produces an anticipatory alert'::text)) WHERE code = 'incident-anticipation-service';

UPDATE service_definitions SET inputs = ARRAY['source-code','configuration-files']::text[], outputs = ARRAY['root-cause-analysis-report']::text[], governance = 'incident-management policy; also draws on infrastructure state and decision history', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['source-code','configuration-files']::text[])), '{outputs}', to_jsonb(ARRAY['root-cause-analysis-report']::text[])), '{governance}', to_jsonb('incident-management policy; also draws on infrastructure state and decision history'::text)) WHERE code = 'root-cause-synthesis-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['engineering-standard']::text[], governance = 'standards-governance policy; draws on evidence from service delivery across the organisation', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['engineering-standard']::text[])), '{governance}', to_jsonb('standards-governance policy; draws on evidence from service delivery across the organisation'::text)) WHERE code = 'standard-synthesis-service';

UPDATE service_definitions SET inputs = ARRAY['capability-maturity-assessment']::text[], outputs = ARRAY['benchmark-report']::text[], governance = 'multi-tenancy/data-sharing policy (Book 3 Ch.42); also produces an identified improvement opportunity alongside the benchmark report', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['capability-maturity-assessment']::text[])), '{outputs}', to_jsonb(ARRAY['benchmark-report']::text[])), '{governance}', to_jsonb('multi-tenancy/data-sharing policy (Book 3 Ch.42); also produces an identified improvement opportunity alongside the benchmark report'::text)) WHERE code = 'capability-benchmarking-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['objective-alignment-report']::text[], governance = 'strategic-governance policy; continuously monitors the active Objective and current engineering state; also produces a drift alert', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['objective-alignment-report']::text[])), '{governance}', to_jsonb('strategic-governance policy; continuously monitors the active Objective and current engineering state; also produces a drift alert'::text)) WHERE code = 'objective-alignment-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['business-analysis-plan']::text[], governance = 'organisational BA standard, Template''s commissioning parameters; also draws on the governing Objective statement, Template/commissioning context, stakeholder complexity, and regulatory context', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['business-analysis-plan']::text[])), '{governance}', to_jsonb('organisational BA standard, Template''s commissioning parameters; also draws on the governing Objective statement, Template/commissioning context, stakeholder complexity, and regulatory context'::text)) WHERE code = 'ba-approach-definition-service';

UPDATE service_definitions SET inputs = ARRAY['requirements-specification','risk-assessment-report']::text[], outputs = ARRAY['requirements-prioritisation-record']::text[], governance = 'prioritisation policy, sponsor approval threshold; also draws on business value criteria and the dependency graph', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['requirements-specification','risk-assessment-report']::text[])), '{outputs}', to_jsonb(ARRAY['requirements-prioritisation-record']::text[])), '{governance}', to_jsonb('prioritisation policy, sponsor approval threshold; also draws on business value criteria and the dependency graph'::text)) WHERE code = 'requirement-prioritisation-service';

UPDATE service_definitions SET inputs = ARRAY['requirements-specification']::text[], outputs = ARRAY['solution-options-analysis']::text[], governance = 'investment/procurement governance policy, architecture standard where options are technical; also draws on the candidate solution options and a cost/risk/value estimate for each', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['requirements-specification']::text[])), '{outputs}', to_jsonb(ARRAY['solution-options-analysis']::text[])), '{governance}', to_jsonb('investment/procurement governance policy, architecture standard where options are technical; also draws on the candidate solution options and a cost/risk/value estimate for each'::text)) WHERE code = 'solution-option-recommendation-service';

UPDATE service_definitions SET inputs = ARRAY['source-code','integration-specification-interface-contracts']::text[], outputs = ARRAY['integration-build']::text[], draft_content = jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['source-code','integration-specification-interface-contracts']::text[])), '{outputs}', to_jsonb(ARRAY['integration-build']::text[])) WHERE code = 'component-integration-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['reuse-assessment']::text[], governance = 'reuse policy, licensing and security vetting standard; also draws on the requirement/design need and the organisational asset inventory', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['reuse-assessment']::text[])), '{governance}', to_jsonb('reuse policy, licensing and security vetting standard; also draws on the requirement/design need and the organisational asset inventory'::text)) WHERE code = 'asset-reuse-service';

UPDATE service_definitions SET inputs = ARRAY['engineering-standard']::text[], outputs = ARRAY['review-report']::text[], governance = 'review policy, separation-of-duties requirement; also draws on the completed artefact under review, code or design', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['engineering-standard']::text[])), '{outputs}', to_jsonb(ARRAY['review-report']::text[])), '{governance}', to_jsonb('review policy, separation-of-duties requirement; also draws on the completed artefact under review, code or design'::text)) WHERE code = 'engineering-review-service';

UPDATE service_definitions SET inputs = ARRAY['root-cause-analysis-report']::text[], outputs = ARRAY['known-error-record']::text[], governance = 'problem-management policy; also draws on operational telemetry trend; also produces the eliminated root causes themselves alongside the known-error record', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['root-cause-analysis-report']::text[])), '{outputs}', to_jsonb(ARRAY['known-error-record']::text[])), '{governance}', to_jsonb('problem-management policy; also draws on operational telemetry trend; also produces the eliminated root causes themselves alongside the known-error record'::text)) WHERE code = 'problem-elimination-service';

UPDATE service_definitions SET inputs = ARRAY['defect-log']::text[], outputs = ARRAY['defect-log']::text[], governance = 'defect-management policy, severity-classification standard; also draws on severity and impact criteria', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['defect-log']::text[])), '{outputs}', to_jsonb(ARRAY['defect-log']::text[])), '{governance}', to_jsonb('defect-management policy, severity-classification standard; also draws on severity and impact criteria'::text)) WHERE code = 'defect-resolution-service';

UPDATE service_definitions SET inputs = ARRAY[]::text[], outputs = ARRAY['vendor-contract','vendor-assessment','vendor-performance-record']::text[], governance = 'procurement policy, third-party risk-management standard; also draws on vendor/supplier candidates, contractual requirements, and third-party risk criteria', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY[]::text[])), '{outputs}', to_jsonb(ARRAY['vendor-contract','vendor-assessment','vendor-performance-record']::text[])), '{governance}', to_jsonb('procurement policy, third-party risk-management standard; also draws on vendor/supplier candidates, contractual requirements, and third-party risk criteria'::text)) WHERE code = 'vendor-management-service';

UPDATE service_definitions SET inputs = ARRAY['capability-maturity-assessment']::text[], outputs = ARRAY['capability-maturity-assessment','capability-evolution-roadmap']::text[], governance = 'capability-ownership mandate, strategic-governance policy — explicitly not line-management authority (§6.11: "should not be confused with traditional line management"); also draws on capability performance and telemetry data, evidence accumulated through service delivery, the current Objective set, and the existing capability portfolio', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['capability-maturity-assessment']::text[])), '{outputs}', to_jsonb(ARRAY['capability-maturity-assessment','capability-evolution-roadmap']::text[])), '{governance}', to_jsonb('capability-ownership mandate, strategic-governance policy — explicitly not line-management authority (§6.11: "should not be confused with traditional line management"); also draws on capability performance and telemetry data, evidence accumulated through service delivery, the current Objective set, and the existing capability portfolio'::text)) WHERE code = 'capability-stewardship-service';

UPDATE service_definitions SET inputs = ARRAY['change-request']::text[], outputs = ARRAY['decision-record']::text[], governance = 'change-management policy, risk-classification standard; also draws on the current schedule of other approved or pending changes and risk-classification criteria; output also includes a conflict assessment against other in-flight changes', draft_content = jsonb_set(jsonb_set(jsonb_set(draft_content, '{inputs}', to_jsonb(ARRAY['change-request']::text[])), '{outputs}', to_jsonb(ARRAY['decision-record']::text[])), '{governance}', to_jsonb('change-management policy, risk-classification standard; also draws on the current schedule of other approved or pending changes and risk-classification criteria; output also includes a conflict assessment against other in-flight changes'::text)) WHERE code = 'change-evaluation-and-scheduling-service';
