-- CR-110 — Route Authority: which badge(s)/role(s) a route requires, as data
-- instead of a literal baked into each route file. See
-- design/change-requests/CR-110-route-authority-table.md and
-- design/route-authority-decisions.md for the full design trace.
--
-- badges/roles are both arrays (AND semantics by default; match_mode='any'
-- for the handful of routes that accept alternates, e.g. Pack's
-- transition/validate). A route with no badge/role requirement at all still
-- gets a row with an empty array — requireBadge(['None'])/requireRole
-- (['None']) are honest, explicit declarations in code today (see
-- middleware/requireBadge.ts's own header comment), and that stays true as
-- data: "checked, and nothing is required" is different from "never
-- checked, no row at all."
--
-- Backfilled from the live, running app's own mounted route tree (Express 5
-- app.router.stack, walked via a one-off instrumented dump — not by hand
-- transcribing route files), so this reflects exactly what's mounted today,
-- not what a grep happened to find.
--
-- Deliberately excluded from this backfill (see CR-110 for why each one
-- doesn't fit a static (method, path) -> badges/roles row):
--   - Routes whose badge is resolved per-request from a URL param, e.g.
--     sdkAuthoring.ts's kind-based defines (/sdk/:slug/new,
--     /sdk/:slug/:draftId/*) and requireRowActionBadge-gated publish/
--     transition routes — one route pattern, many possible badges depending
--     on runtime data. Stays on its existing dynamic-resolution mechanism.
--   - Hand-rolled inline gates that never call requireBadge/requireRole at
--     all: requireAuthorityAdmin (/sdk/authority/*), requireOntologyAdmin
--     (/sdk/ontology/*).
--   - /aisworg/demo, gated at the router-mount level
--     (app.use("/aisworg/demo", requireRole(...), demoRouter)), not
--     per-route — req.route isn't set yet at that point, so it doesn't fit
--     the same per-route lookup key.
--   - The legacy string-argument requireRole (middleware/auth.js:
--     requireRole('general'|'super')), used by routes/web/public.js and
--     routes/web/auth.js — a different, older mechanism, explicitly kept
--     untouched per its own header comment, not part of this effort.
--   - Every route with no requireBadge/requireRole call at all today (most
--     of the SEU API layer: evidence, decisions, knowledge, reviews,
--     compliance, obligations, tenants, execution-targets, attention-items,
--     external-interactions, findings, work-items, etc.) — nothing to
--     record; adding a row for these would assert a gate that doesn't
--     exist.
--   - CRUD routes for this table itself (don't exist yet — built separately,
--     gated by ROUTE_AUTHORITY_ADMIN_BADGE env var, not by this table).

CREATE TABLE IF NOT EXISTS route_authority (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  method      TEXT NOT NULL,
  path        TEXT NOT NULL,
  badges      TEXT[] NOT NULL DEFAULT '{}',
  roles       TEXT[] NOT NULL DEFAULT '{}',
  match_mode  TEXT NOT NULL DEFAULT 'all' CHECK (match_mode IN ('all', 'any')),
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT route_authority_method_path_unique UNIQUE (method, path)
);

INSERT INTO route_authority (method, path, badges, roles, match_mode) VALUES
  ('GET', '/', '{}', '{}', 'all'),
  ('GET', '/aisworg/login', '{}', '{}', 'all'),
  ('GET', '/aisworg/logout', '{}', '{}', 'all'),
  ('GET', '/aisworg/auth/login', '{}', '{}', 'all'),
  ('POST', '/aisworg/auth/login', '{}', '{}', 'all'),
  ('GET', '/aisworg/auth/logout', '{}', '{}', 'all'),
  ('GET', '/aisworg/auth/reset-password', '{}', '{}', 'all'),
  ('POST', '/aisworg/auth/reset-password', '{}', '{}', 'all'),
  ('GET', '/aisworg', '{}', '{}', 'all'),
  -- /aisworg/api/seu/*
  ('POST', '/aisworg/api/seu/objectives/:id/transition/achieve',   ARRAY['objective_achieve'],   '{}', 'all'),
  ('POST', '/aisworg/api/seu/objectives/:id/transition/activate',  ARRAY['objective_activate'],  '{}', 'all'),
  ('POST', '/aisworg/api/seu/objectives/:id/transition/archive',   ARRAY['objective_archive'],   '{}', 'all'),
  ('POST', '/aisworg/api/seu/objectives/:id/transition/reject',    ARRAY['objective_reject'],    '{}', 'all'),
  ('POST', '/aisworg/api/seu/objectives/:id/transition/retire',    ARRAY['objective_retire'],    '{}', 'all'),
  ('POST', '/aisworg/api/seu/objectives/:id/transition/supersede', ARRAY['objective_supersede'], '{}', 'all'),
  ('POST', '/aisworg/api/seu/objectives/:id/update',               ARRAY['objective_propose'],   '{}', 'all'),
  ('GET',  '/aisworg/api/seu/objectives/:id',                      '{}', '{}', 'all'),
  ('GET',  '/aisworg/api/seu/objectives/suggest-capabilities',     '{}', '{}', 'all'),
  ('GET',  '/aisworg/api/seu/objectives',                          '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/objectives',                          ARRAY['objective_propose'],   '{}', 'all'),
  ('POST', '/aisworg/api/seu/packs/:id/transition/activate',       ARRAY['pack_activate'],       '{}', 'all'),
  ('POST', '/aisworg/api/seu/packs/:id/transition/archive',        ARRAY['pack_archive'],        '{}', 'all'),
  ('POST', '/aisworg/api/seu/packs/:id/transition/publish',        ARRAY['pack_publish'],        '{}', 'all'),
  ('POST', '/aisworg/api/seu/packs/:id/transition/reject',         ARRAY['pack_reject', 'pack_validate'], '{}', 'any'),
  ('POST', '/aisworg/api/seu/packs/:id/transition/retire',         ARRAY['pack_retire'],         '{}', 'all'),
  ('POST', '/aisworg/api/seu/packs/:id/transition/validate',       ARRAY['pack_validate', 'pack_define', 'pack_reject'], '{}', 'any'),
  ('GET',  '/aisworg/api/seu/packs',                                '{}', '{}', 'all'),

  -- /aisworg/seu/* (web)
  ('GET',  '/aisworg/seu/capabilities',                            '{}', ARRAY['participant'], 'all'),
  ('POST', '/aisworg/seu/deliverable-definitions/:id/copy',        '{}', ARRAY['participant'], 'all'),
  ('GET',  '/aisworg/seu/deliverable-definitions',                 '{}', ARRAY['participant'], 'all'),
  ('POST', '/aisworg/seu/identity/badges/:id/update',              ARRAY['identity_manage'], '{}', 'all'),
  ('GET',  '/aisworg/seu/identity/badges',                         ARRAY['identity_manage'], '{}', 'all'),
  ('GET',  '/aisworg/seu/identity/tenants',                        ARRAY['root'], '{}', 'all'),
  ('POST', '/aisworg/seu/identity/tenants',                        ARRAY['root'], '{}', 'all'),
  ('POST', '/aisworg/seu/identity/users/:id/update',               ARRAY['identity_manage'], '{}', 'all'),
  ('GET',  '/aisworg/seu/identity/users',                          ARRAY['identity_manage'], '{}', 'all'),
  ('POST', '/aisworg/seu/identity/users',                          ARRAY['identity_manage'], '{}', 'all'),
  ('GET',  '/aisworg/seu/identity',                                ARRAY['root'], '{}', 'all'),
  ('GET',  '/aisworg/seu/objectives/:id/children',                 '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/comments',                 '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/commission',               ARRAY['seu_commission'], '{}', 'all'),
  ('GET',  '/aisworg/seu/objectives/:id/compose-ebm',              ARRAY['seu_commission'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/compose-ebm',              ARRAY['seu_commission'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/delete',                   ARRAY['objective_propose'], '{}', 'all'),
  ('GET',  '/aisworg/seu/objectives/:id/edit',                     ARRAY['objective_propose'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/move',                     ARRAY['objective_propose'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/retire',                   ARRAY['objective_retire'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/submit',                   ARRAY['objective_propose'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/transition/activate',      ARRAY['objective_activate'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/transition/archive',       ARRAY['objective_archive'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/transition/reject',        ARRAY['objective_reject'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/transition/retire',        ARRAY['objective_retire'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/transition/supersede',     ARRAY['objective_supersede'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/update',                   ARRAY['objective_propose'], '{}', 'all'),
  ('GET',  '/aisworg/seu/objectives/:id/validate-commission',      ARRAY['seu_commission'], '{}', 'all'),
  ('POST', '/aisworg/seu/objectives/:id/validate-commission',      ARRAY['seu_commission'], '{}', 'all'),
  ('GET',  '/aisworg/seu/objectives/:id',                          '{}', '{}', 'all'),
  ('GET',  '/aisworg/seu/objectives/new',                          ARRAY['objective_propose'], '{}', 'all'),
  ('GET',  '/aisworg/seu/objectives',                              '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/objectives',                              ARRAY['objective_propose'], '{}', 'all'),
  ('GET',  '/aisworg/seu/packs',                                   '{}', ARRAY['participant'], 'all'),
  ('GET',  '/aisworg/seu/participants',                            '{}', ARRAY['participant'], 'all'),
  ('POST', '/aisworg/seu/policy-definitions/:id/copy',             '{}', ARRAY['participant'], 'all'),
  ('GET',  '/aisworg/seu/policy-definitions',                      '{}', ARRAY['participant'], 'all'),
  ('POST', '/aisworg/seu/profiles/:id/copy',                       '{}', ARRAY['participant'], 'all'),
  ('GET',  '/aisworg/seu/profiles',                                '{}', ARRAY['participant'], 'all'),
  ('GET',  '/aisworg/seu/sdk/schema-registry/:id',                 ARRAY['root'], '{}', 'all'),
  ('GET',  '/aisworg/seu/sdk/schema-registry/new',                 ARRAY['root'], '{}', 'all'),
  ('GET',  '/aisworg/seu/sdk/schema-registry',                     ARRAY['root'], '{}', 'all'),
  ('POST', '/aisworg/seu/sdk/schema-registry',                     ARRAY['root'], '{}', 'all'),
  ('POST', '/aisworg/seu/service-definitions/:id/copy',            '{}', ARRAY['participant'], 'all'),
  ('GET',  '/aisworg/seu/service-definitions',                     '{}', ARRAY['participant'], 'all'),
  ('POST', '/aisworg/seu/templates/:id/copy',                      '{}', ARRAY['participant'], 'all'),
  ('GET',  '/aisworg/seu/templates',                                '{}', ARRAY['participant'], 'all'),
  
  ('GET', '/aisworg/api/seu/attention-items', '{}', ARRAY['participant'], 'all'),
  ('POST', '/aisworg/api/seu/attention-items/:id/transition', '{}', ARRAY['participant'], 'all'),
  ('POST', '/aisworg/api/seu/commission', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/compliance/frameworks', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/compliance/requirements', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/decisions', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/decisions', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/decisions/:id/transition', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/deliverables/:id/traceability', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/deliverables/:id/transition', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/evidence', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/evidence', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/evidence/:id/link', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/evidence/:id/transition', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/evidence/:id/validate', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/execution-targets', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/execution-targets/:capabilityId', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/external-interactions', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/external-interactions', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/external-interactions/:id/transition', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/findings/:id/convert-to-obligation', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/findings/:id/transition', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/knowledge', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/knowledge', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/knowledge/:id/promote-scope', '{}', '{}', 'all'),
  ('PATCH', '/aisworg/api/seu/knowledge/:id/references', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/knowledge/:id/transition', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/knowledge/:id/validation-notes', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/knowledge/:id/validation-notes', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/knowledge/capital', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/obligations', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/obligations', '{}', '{}', 'all'),
  ('PATCH', '/aisworg/api/seu/obligations/:id', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/obligations/:id/transition', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/ontology/concepts', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/profiles', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/reviews', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/reviews', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/reviews/:id/findings', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/reviews/:id/findings', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/reviews/:id/transition', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/services', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/seus/:id', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/seus/:id/compliance', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/seus/:id/compliance/history', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/seus/:id/compliance/report', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/seus/:id/compliance/waivers', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/seus/:id/deliverables', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/seus/:id/events', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/seus/:id/governance-model', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/seus/:id/quality-gate-waivers', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/seus/:id/quality-gate-waivers', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/telemetry', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/templates', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/tenants', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/tenants', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/tenants/:id/aliases', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/tenants/:id/aliases', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/tenants/:id/contract', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/tenants/:id/contract', '{}', '{}', 'all'),
  ('GET', '/aisworg/api/seu/tenants/:id/vocabulary', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/work-items/:id/result', '{}', '{}', 'all'),
  ('POST', '/aisworg/api/seu/work-items/sweep-stalled', '{}', '{}', 'all'),
  ('GET', '/aisworg/auth/disabled', '{}', '{}', 'all'),
  ('GET', '/aisworg/auth/forgot-password', '{}', '{}', 'all'),
  ('POST', '/aisworg/auth/forgot-password', '{}', '{}', 'all'),
  ('GET', '/aisworg/auth/google', '{}', '{}', 'all'),
  ('GET', '/aisworg/auth/google/callback', '{}', '{}', 'all'),
  ('GET', '/aisworg/auth/users', '{}', ARRAY['superuser'], 'all'),
  ('POST', '/aisworg/auth/users/create', '{}', ARRAY['superuser'], 'all'),
  ('POST', '/aisworg/auth/users/resend', '{}', ARRAY['superuser'], 'all'),
  ('POST', '/aisworg/auth/users/role', '{}', ARRAY['superuser'], 'all'),
  ('POST', '/aisworg/auth/users/toggle', '{}', ARRAY['superuser'], 'all'),
  ('GET', '/aisworg/auth/verify', '{}', '{}', 'all'),
  ('POST', '/aisworg/auth/verify', '{}', '{}', 'all'),
  ('POST', '/aisworg/demo/tts', '{}', '{}', 'all'),
  ('GET', '/aisworg/demo/voice-config', '{}', '{}', 'all'),
  ('GET', '/aisworg/quickview', '{}', '{}', 'all'),
  ('POST', '/aisworg/quickview/seus/:seuId/obligations', '{}', '{}', 'all'),
  ('POST', '/aisworg/quickview/work-items/:workItemId/complete', '{}', '{}', 'all'),
  ('GET', '/aisworg/settings', '{}', ARRAY['superuser'], 'all'),
  ('POST', '/aisworg/settings/:key', '{}', ARRAY['superuser'], 'all'),
  ('GET', '/aisworg/seu', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/attention', '{}', ARRAY['participant'], 'all'),
  ('POST', '/aisworg/seu/attention/:id/transition', '{}', ARRAY['participant'], 'all'),
  ('GET', '/aisworg/seu/authority/mapping', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/authority/mapping/add', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/authority/mapping/edit-trigger', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/authority/mapping/retire', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('GET', '/aisworg/seu/authority/nouns', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/authority/nouns/add', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/authority/nouns/retire', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('GET', '/aisworg/seu/authority/transition-definitions/:id', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('GET', '/aisworg/seu/authority/transition-definitions/:id/edit', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/authority/transition-definitions/:id/update', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/authority/transition-definitions/add', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/authority/transition-definitions/retire', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('GET', '/aisworg/seu/authority/verbs', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/authority/verbs/add', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/authority/verbs/retire', ARRAY['transitiondefinition_define'], '{}', 'all'),
  ('POST', '/aisworg/seu/dev/act-as', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/dev/act-as/reset', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/knowledge/capital', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/route-authority', ARRAY['root'], '{}', 'all'),
  ('POST', '/aisworg/seu/route-authority', ARRAY['root'], '{}', 'all'),
  ('POST', '/aisworg/seu/route-authority/:id/delete', ARRAY['root'], '{}', 'all'),
  ('GET', '/aisworg/seu/route-authority/:id/edit', ARRAY['root'], '{}', 'all'),
  ('POST', '/aisworg/seu/route-authority/:id/update', ARRAY['root'], '{}', 'all'),
  ('GET', '/aisworg/seu/route-authority/new', ARRAY['root'], '{}', 'all'),
  ('GET', '/aisworg/seu/sdk/:slug', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/sdk/:slug', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/sdk/:slug/:draftId', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/sdk/:slug/:draftId/compose', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/sdk/:slug/:draftId/import', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/sdk/:slug/:draftId/publish', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/sdk/:slug/:draftId/save', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/sdk/:slug/:draftId/transition', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/sdk/:slug/new', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/sdk/ontology', ARRAY['ontology_define','ontology_manage'], '{}', 'any'),
  ('POST', '/aisworg/seu/sdk/ontology/add', ARRAY['ontology_define','ontology_manage'], '{}', 'any'),
  ('POST', '/aisworg/seu/sdk/ontology/archive', ARRAY['ontology_define','ontology_manage'], '{}', 'any'),
  ('POST', '/aisworg/seu/sdk/ontology/compose', ARRAY['ontology_define','ontology_manage'], '{}', 'any'),
  ('POST', '/aisworg/seu/sdk/ontology/deprecate', ARRAY['ontology_define','ontology_manage'], '{}', 'any'),
  ('GET', '/aisworg/seu/sdk/ontology/metadata', ARRAY['ontology_define','ontology_manage'], '{}', 'any'),
  ('POST', '/aisworg/seu/sdk/ontology/quick-retire', ARRAY['ontology_define','ontology_manage'], '{}', 'any'),
  ('POST', '/aisworg/seu/sdk/ontology/retire', ARRAY['ontology_define','ontology_manage'], '{}', 'any'),
  ('POST', '/aisworg/seu/sdk/ontology/update-meta', ARRAY['ontology_define','ontology_manage'], '{}', 'any'),
  ('GET', '/aisworg/seu/services', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/seus', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/seus/:id', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/attention-items', '{}', ARRAY['participant'], 'all'),
  ('POST', '/aisworg/seu/seus/:id/attention-items/:attentionItemId/transition', '{}', ARRAY['participant'], 'all'),
  ('POST', '/aisworg/seu/seus/:id/capabilities/:capabilityId/fulfil', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/capabilities/:capabilityId/participant/:participantId/replace', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/capabilities/:capabilityId/release', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/seus/:id/compliance', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/compliance/waivers', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/decisions', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/decisions/:decisionId/transition', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/deliverables/:deliverableId/transition', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/seus/:id/ebm', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/ebm/transition', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/evidence', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/evidence/:evidenceId/link', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/evidence/:evidenceId/transition', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/evidence/:evidenceId/validate', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/external-interactions', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/external-interactions/:interactionId/transition', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/findings/:findingId/convert', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/findings/:findingId/transition', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/knowledge', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/knowledge/:knowledgeItemId/promote-scope', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/knowledge/:knowledgeItemId/transition', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/obligations/:obligationId/revise', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/obligations/:obligationId/transition', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/seus/:id/reviews', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/reviews', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/reviews/:reviewId/findings', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/reviews/:reviewId/transition', '{}', '{}', 'all'),
  ('POST', '/aisworg/seu/seus/:id/work-items/:workItemId/complete', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/seus/:id/work-queue', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/seus/new', '{}', '{}', 'all'),
  ('GET', '/aisworg/seu/telemetry', '{}', '{}', 'all')
ON CONFLICT (method, path) DO UPDATE SET
  badges      = EXCLUDED.badges,
  roles       = EXCLUDED.roles,
  match_mode  = EXCLUDED.match_mode,
  updated_at  = NOW();
