import { createRequire } from "module";
const require = createRequire(import.meta.url);
const express = require("express");
const router = express.Router();

import { router as objectivesRouter } from "./objectives.js";
import { router as templatesRouter } from "./templates.js";
import { router as profilesRouter } from "./profiles.js";
import { router as seusRouter } from "./seus.js";
import { router as deliverablesRouter } from "./deliverables.js";
import { router as servicesRouter } from "./services.js";
import { router as obligationsRouter } from "./obligations.js";
import { router as evidenceRouter } from "./evidence.js";
import { router as knowledgeRouter } from "./knowledge.js";
import { router as decisionsRouter } from "./decisions.js";
import { router as telemetryRouter } from "./telemetry.js";
import { router as attentionItemsRouter } from "./attentionItems.js";
import { router as externalInteractionsRouter } from "./externalInteractions.js";
import { router as packsRouter } from "./packs.js";
import { router as workItemsRouter } from "./workItems.js";
import { router as executionTargetsRouter } from "./executionTargets.js";
import { router as tenantsRouter } from "./tenants.js";
import { router as reviewsRouter } from "./reviews.js";
import { router as complianceRouter } from "./compliance.js";
import { router as ontologyRouter } from "./ontology.js";

router.use(objectivesRouter);
router.use(templatesRouter);
router.use(profilesRouter);
router.use(seusRouter);
router.use(deliverablesRouter);
router.use(servicesRouter);
router.use(obligationsRouter);
router.use(evidenceRouter);
router.use(knowledgeRouter);
router.use(decisionsRouter);
router.use(telemetryRouter);
router.use(attentionItemsRouter);
router.use(externalInteractionsRouter);
router.use(packsRouter);
router.use(workItemsRouter);
router.use(executionTargetsRouter);
router.use(tenantsRouter);
router.use(reviewsRouter);
router.use(complianceRouter);
router.use(ontologyRouter);

export { router };
